import React, { useState } from 'react';
import {
  BookOpen, Globe, Users, Activity, Link2, ChevronDown, ChevronUp, ExternalLink
} from 'lucide-react';

interface Entry {
  name: string;
  where: string;
  what: string;
  details: string[];
  envVars?: string[];
}

interface Section {
  title: string;
  icon: React.ReactNode;
  intro: string;
  entries: Entry[];
}

const SECTIONS: Section[] = [
  {
    title: 'Public links generated by TaskTracker',
    icon: <Link2 className="w-5 h-5 text-blue-500" />,
    intro: 'These pages need no login — anyone with the link can open them. Treat the link itself as the access control.',
    entries: [
      {
        name: 'Client Monthly Report',
        where: '/report/:clientSlug/:year/:month',
        what: "A client's billing report for one month: completed tasks, hours, revenue, supplies, and a 6-month trend. Copy the link from the \"Copy Client URL\" / \"Copy Public Report URL\" button on the Client Dashboard or the Reports page.",
        details: [
          'The client can download the same report as PDF or CSV from that page.',
          'If "Task selection" is turned on for a client (Client Dashboard → client settings), the client can also tick which tasks they\'re claiming on that report — saved back to that task, doesn\'t touch anything outside that client + month.',
          'Revenue shown always uses the rate that was in effect for that year (client.yearlyRates), not today\'s rate.'
        ]
      },
      {
        name: 'Public Status Page',
        where: '/status/:slug',
        what: 'An uptime/status page for a client or service. Created under Integrations → Status Pages, where you set the slug, organization name, and description.',
        details: [
          'Shows whichever monitors are mapped to it via Monitors → monitor feeds (see below).'
        ]
      },
      {
        name: 'Onboarding / Offboarding Request Form',
        where: '/onboarding',
        what: 'A static public form (same link for everyone) where a manager requests access setup ("alta") or removal ("baja") for an employee — access types, effective date, notes.',
        details: [
          'Submissions land in Altas / Bajas (admin panel), where each access type gets its own checklist item, CC recipients can be added, and every update/checklist change emails the requester (and CC list) via Resend.',
          'A request sitting untouched for ONBOARDING_STALE_DAYS gets a one-time reminder sent to ADMIN_NOTIFICATION_EMAIL.'
        ],
        envVars: ['RESEND_API_KEY', 'RESEND_FROM_EMAIL', 'ADMIN_NOTIFICATION_EMAIL', 'EMAIL_REPLY_TO', 'ONBOARDING_STALE_DAYS', 'PUBLIC_APP_URL']
      }
    ]
  },
  {
    title: 'Second-system integrations',
    icon: <Activity className="w-5 h-5 text-purple-500" />,
    intro: "Data moving between TaskTracker and something else running outside it — another Docker container on the same host, or an external service.",
    entries: [
      {
        name: 'Client Data Export (→ "servicios cliente")',
        where: 'Integrations, background job',
        what: "Once an hour, TaskTracker writes clients.json (active clients only: id, name, slug, email, phone, contactPerson) into a folder shared with the other client-services container on this host. One-way — nothing is ever read back.",
        details: [
          'Leave CLIENT_EXPORT_HOST_DIR empty and this does nothing — no folder, no writes.',
          'Force a write immediately with POST /api/admin/client-export/run instead of waiting for the hourly job.'
        ],
        envVars: ['CLIENT_EXPORT_HOST_DIR']
      },
      {
        name: 'Onboarding/Offboarding Import (NAS drop folder)',
        where: 'Background job, once a day',
        what: 'A different system on the same host can drop onboarding/offboarding report JSON files into a shared folder. TaskTracker picks them up once a day and creates an onboarding_requests row per pending action, matched to a client by name.',
        details: [
          'Processed files move to <dir>/processed; invalid ones move to <dir>/failed.',
          'Leave ONBOARDING_IMPORT_HOST_DIR empty and this does nothing — no folder, no import.',
          'Runs at ONBOARDING_IMPORT_HOUR local time, where "local" is set by TZ.'
        ],
        envVars: ['ONBOARDING_IMPORT_HOST_DIR', 'ONBOARDING_IMPORT_HOUR', 'TZ']
      },
      {
        name: 'External Portal Webhook',
        where: 'Fires on task open/close',
        what: 'Opening or closing a Problem/Change task POSTs a JSON summary ({ event: "opened" | "closed", ... }) to an external URL, if one is configured.',
        details: [
          "Sent with Authorization: Bearer <token> when EXTERNAL_PORTAL_WEBHOOK_TOKEN is also set.",
          'Leave EXTERNAL_PORTAL_WEBHOOK_URL empty and nothing is sent.'
        ],
        envVars: ['EXTERNAL_PORTAL_WEBHOOK_URL', 'EXTERNAL_PORTAL_WEBHOOK_TOKEN']
      },
      {
        name: 'Monitor Integration',
        where: 'Integrations → Monitors',
        what: "TaskTracker reads an external monitoring feed's status JSON (e.g. an uptime checker) through a server-side proxy (avoids CORS) and maps each monitor to a client/project, optionally surfacing it on a Public Status Page.",
        details: [
          'This is TaskTracker pulling data in — the external monitor never pushes anything to TaskTracker.'
        ]
      },
      {
        name: 'Transactional Email (Resend)',
        where: 'Onboarding/offboarding confirmations, task close summaries, stale-request reminders',
        what: 'All outbound email goes through Resend. Without RESEND_API_KEY set, these sends are skipped (logged, not queued) rather than failing the request.',
        details: [],
        envVars: ['RESEND_API_KEY', 'RESEND_FROM_EMAIL', 'EMAIL_REPLY_TO']
      }
    ]
  },
  {
    title: 'Not currently in use',
    icon: <Globe className="w-5 h-5 text-gray-400" />,
    intro: '',
    entries: [
      {
        name: 'Supabase',
        where: '—',
        what: "There's no Supabase code anywhere in this app — it was only ever placeholder variables in .env.example, now removed. If you see Supabase mentioned in old notes, it doesn't apply to this build.",
        details: []
      }
    ]
  }
];

function EntryCard({ entry }: { entry: Entry }) {
  const [open, setOpen] = useState(false);
  const hasMore = entry.details.length > 0 || (entry.envVars && entry.envVars.length > 0);

  return (
    <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 bg-white dark:bg-gray-800">
      <div className="flex items-start justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <h3 className="font-semibold text-gray-900 dark:text-white">{entry.name}</h3>
            {entry.where !== '—' && (
              <code className="text-xs px-1.5 py-0.5 rounded bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 flex items-center gap-1">
                {entry.where.startsWith('/') && <ExternalLink className="w-3 h-3" />}
                {entry.where}
              </code>
            )}
          </div>
          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">{entry.what}</p>
        </div>
        {hasMore && (
          <button
            onClick={() => setOpen(!open)}
            className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 flex-shrink-0"
            aria-label={open ? 'Collapse details' : 'Expand details'}
          >
            {open ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
        )}
      </div>

      {open && hasMore && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-700 space-y-3">
          {entry.details.length > 0 && (
            <ul className="space-y-1.5">
              {entry.details.map((d, i) => (
                <li key={i} className="text-sm text-gray-600 dark:text-gray-400 flex gap-2">
                  <span className="text-gray-300 dark:text-gray-600 flex-shrink-0">•</span>
                  <span>{d}</span>
                </li>
              ))}
            </ul>
          )}
          {entry.envVars && entry.envVars.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {entry.envVars.map((v) => (
                <code key={v} className="text-xs px-1.5 py-0.5 rounded bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300">
                  {v}
                </code>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export function ManualPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-lg bg-blue-50 dark:bg-blue-900/20 flex items-center justify-center flex-shrink-0">
          <BookOpen className="w-5 h-5 text-blue-600 dark:text-blue-400" />
        </div>
        <div>
          <h1 className="text-2xl font-semibold text-gray-900 dark:text-white">Manual</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">
            Every place TaskTracker talks to something outside itself: public links it hands out, and data it sends or receives from another system. Configuration (env vars) is set on the server — this page is just a map of what exists and where it lives.
          </p>
        </div>
      </div>

      {SECTIONS.map((section) => (
        <div key={section.title}>
          <div className="flex items-center gap-2 mb-1">
            {section.icon}
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">{section.title}</h2>
          </div>
          {section.intro && (
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">{section.intro}</p>
          )}
          <div className="space-y-3">
            {section.entries.map((entry) => (
              <EntryCard key={entry.name} entry={entry} />
            ))}
          </div>
        </div>
      ))}

      <div className="flex items-center gap-2 text-xs text-gray-400 dark:text-gray-500 pt-4 border-t border-gray-100 dark:border-gray-800">
        <Users className="w-3.5 h-3.5" />
        <span>Update this page whenever a new integration, public link, or import/export job is added.</span>
      </div>
    </div>
  );
}
