import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

// Cenas IT Solutions brand palette. Structure (headers, titles, dividers)
// uses Brand Dark; totals/KPIs/highlights use the Teal accent - keeping
// those two roles visually distinct is what makes a scanned report read
// as "here's the structure" vs "here's the number that matters".
export const BRAND_DARK: [number, number, number] = [11, 25, 44];        // #0B192C
export const BRAND_TEAL: [number, number, number] = [6, 182, 212];       // #06B6D4
export const NEUTRAL_BG: [number, number, number] = [248, 250, 252];     // #F8FAFC
export const NEUTRAL_ROW: [number, number, number] = [241, 245, 249];    // slate-100, table zebra striping
export const NEUTRAL_BORDER: [number, number, number] = [226, 232, 240]; // #E2E8F0
export const NEUTRAL_TEXT: [number, number, number] = [51, 65, 85];      // #334155
export const NEUTRAL_TEXT_MUTED: [number, number, number] = [100, 116, 139]; // slate-500
export const NEUTRAL_TEXT_LIGHT: [number, number, number] = [148, 163, 184]; // slate-400, footer fine print
export const WHITE: [number, number, number] = [255, 255, 255];
export const TEAL_WASH: [number, number, number] = [236, 254, 255];      // cyan-50, summary box fill
export const TEAL_INK: [number, number, number] = [14, 116, 144];        // cyan-800, text on teal wash
export const TEAL_DEEP: [number, number, number] = [8, 145, 178];        // cyan-700, emphasis on teal wash

// Task-type accents, shared with the client portal so a task reads the
// same color whether you're looking at the PDF or the web.
export const TASK_INCIDENT: [number, number, number] = [220, 38, 38];  // red-600 - stops the operation, must stand out
export const TASK_REQUEST: [number, number, number] = BRAND_TEAL;      // day-to-day work - the brand accent
export const TASK_PROBLEM: [number, number, number] = [245, 158, 11];  // amber-500 - recurring, needs investigation
export const TASK_CHANGE: [number, number, number] = [139, 92, 246];   // violet-500 - structured improvement/project

export const TASK_TYPE_COLORS: Record<string, [number, number, number]> = {
  Incident: TASK_INCIDENT, Incidents: TASK_INCIDENT,
  Request: TASK_REQUEST, Requests: TASK_REQUEST,
  Problem: TASK_PROBLEM, Problems: TASK_PROBLEM,
  Change: TASK_CHANGE, Changes: TASK_CHANGE
};

// Falls back to the Cenas mark when a client hasn't uploaded their own
// logo in Company Settings. The report page background is white, so this
// is the dark-text variant meant for light backgrounds.
export const DEFAULT_LOGO_URL = 'https://landing.cenas.uy/assets/brand/logo-light.png';

interface CompanySettings {
  company_name: string;
  logo_url: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  tax_id: string | null;
  pdf_footer_message?: string | null;
}

export interface ReportTask {
  id: string;
  clientId: string;
  projectId: string;
  description: string;
  hours?: number;
  cost?: number;
  date: string;
  type: string;
  status?: string;
  priority?: string;
  finished?: boolean;
  notes?: string;
  isRecurring?: boolean;
  approvalStatus?: string;
  vendor?: string;
  approvedBy?: string;
  receiptRef?: string;
}

export interface ReportClient {
  id: string;
  name: string;
  hourlyRate: number;
  contactPerson?: string;
  email?: string;
}

export interface ReportProject {
  id: string;
  name: string;
}

export class PDFExporter {
  private doc: jsPDF;
  private companySettings: CompanySettings;
  private footerContext: string = '';
  currentY: number = 20;

  constructor(companySettings: CompanySettings) {
    this.doc = new jsPDF();
    this.companySettings = companySettings;
  }

  // Shown on every page's footer, before "Generated by ...", e.g.
  // "Acme Corp — March 2026" or "Acme Corp — Jan 2025 – Jun 2025" - so a
  // printed page is identifiable on its own without the cover page.
  setFooterContext(text: string) {
    this.footerContext = text;
  }

  private async loadLogo(): Promise<{ data: string; format: string } | null> {
    const logoUrl = this.companySettings.logo_url || DEFAULT_LOGO_URL;
    try {
      // If already a data URL, use it directly
      if (logoUrl.startsWith('data:')) {
        const match = logoUrl.match(/^data:image\/(\w+);base64,/);
        const format = match ? match[1].toUpperCase() : 'PNG';
        return { data: logoUrl, format: format === 'JPEG' ? 'JPEG' : format === 'JPG' ? 'JPEG' : 'PNG' };
      }
      // A plain <img> loads a cross-origin logo fine, but embedding it in
      // the PDF means fetch()-ing the actual bytes, which the browser
      // blocks unless the remote host sends CORS headers - most static
      // asset hosts (including the Cenas brand host) don't. Route it
      // through our own logo proxy instead, which sidesteps that.
      let url = logoUrl;
      if (logoUrl.startsWith('http')) {
        try {
          if (new URL(logoUrl).hostname === 'landing.cenas.uy') {
            const apiBase = import.meta.env.MODE === 'production' ? '' : (import.meta.env.VITE_API_URL || 'http://localhost:3000');
            url = `${apiBase}/api/logo-proxy`;
          }
        } catch { /* malformed URL - fall through to a direct fetch */ }
      } else {
        // Make relative URLs absolute
        url = `${window.location.origin}${logoUrl.startsWith('/') ? '' : '/'}${logoUrl}`;
      }
      const response = await fetch(url);
      if (!response.ok) return null;
      const blob = await response.blob();
      const format = blob.type.includes('jpeg') || blob.type.includes('jpg') ? 'JPEG' : 'PNG';
      return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve({ data: reader.result as string, format });
        reader.onerror = () => resolve(null);
        reader.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  }

  async addHeader(title: string) {
    this.currentY = 15;

    const logo = await this.loadLogo();
    if (logo) {
      try {
        // Logo: up to 50mm wide, 20mm tall, preserving space
        this.doc.addImage(logo.data, logo.format, 15, this.currentY, 50, 20);
      } catch { /* ignore logo if it still fails */ }
    }

    let companyY = this.currentY;
    const rightMargin = 195;

    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...NEUTRAL_TEXT);
    this.doc.text(this.companySettings.company_name, rightMargin, companyY, { align: 'right' });
    companyY += 5;

    this.doc.setFontSize(8);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...NEUTRAL_TEXT_MUTED);

    if (this.companySettings.address) {
      const addressLines = this.doc.splitTextToSize(this.companySettings.address, 75);
      addressLines.forEach((line: string) => {
        this.doc.text(line, rightMargin, companyY, { align: 'right' });
        companyY += 3.5;
      });
    }
    if (this.companySettings.phone) { this.doc.text(this.companySettings.phone, rightMargin, companyY, { align: 'right' }); companyY += 3.5; }
    if (this.companySettings.email) { this.doc.text(this.companySettings.email, rightMargin, companyY, { align: 'right' }); companyY += 3.5; }
    if (this.companySettings.website) { this.doc.text(this.companySettings.website, rightMargin, companyY, { align: 'right' }); companyY += 3.5; }

    this.currentY = Math.max(this.currentY + 28, companyY + 3);

    this.doc.setDrawColor(...BRAND_DARK);
    this.doc.setLineWidth(0.5);
    this.doc.line(15, this.currentY, 195, this.currentY);
    this.currentY += 8;

    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...BRAND_DARK);
    this.doc.text(title, 15, this.currentY);
    this.currentY += 10;

    return this.currentY;
  }

  addSection(title: string, content: Record<string, string>) {
    const rows = Object.keys(content).length;
    const blockHeight = rows * 5.5 + 10;

    // Page break if section won't fit
    if (this.currentY + blockHeight > 270) {
      this.doc.addPage();
      this.currentY = 20;
    }

    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...NEUTRAL_TEXT);
    this.doc.text(title, 15, this.currentY);
    this.currentY += 6;

    this.doc.setFillColor(...NEUTRAL_BG);
    this.doc.roundedRect(15, this.currentY - 3, 180, rows * 5.5 + 4, 2, 2, 'F');
    this.currentY += 2;

    this.doc.setFontSize(9);
    this.doc.setTextColor(...NEUTRAL_TEXT_MUTED);

    Object.entries(content).forEach(([key, value]) => {
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(`${key}:`, 20, this.currentY);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...NEUTRAL_TEXT);
      // Truncate long values so they don't overflow the box
      const safeValue = this.doc.splitTextToSize(value, 120)[0];
      this.doc.text(safeValue, 65, this.currentY);
      this.doc.setTextColor(...NEUTRAL_TEXT_MUTED);
      this.currentY += 5.5;
    });

    this.currentY += 6;
  }

  // reserveHeight: extra space (mm) the caller knows is coming right after
  // the title - e.g. a table's header row plus a row or two of data - so we
  // don't strand the title alone at the bottom of a page with its content
  // pushed to the next one.
  addSectionTitle(title: string, reserveHeight: number = 0) {
    if (this.currentY + 8 + reserveHeight > 272) { this.doc.addPage(); this.currentY = 20; }
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...NEUTRAL_TEXT);
    this.doc.text(title, 15, this.currentY);
    this.currentY += 8;
  }

  addTable(headers: string[], rows: any[][], options?: any) {
    const pageWidth = this.doc.internal.pageSize.getWidth();
    const availableWidth = pageWidth - 28;

    (this.doc as any).autoTable({
      startY: this.currentY,
      head: [headers],
      body: rows,
      theme: 'striped',
      margin: { left: 14, right: 14 },
      tableWidth: availableWidth,
      headStyles: {
        fillColor: BRAND_DARK,
        textColor: WHITE,
        fontStyle: 'bold',
        fontSize: 10
      },
      bodyStyles: { fontSize: 9, textColor: NEUTRAL_TEXT },
      alternateRowStyles: { fillColor: NEUTRAL_ROW },
      styles: { overflow: 'linebreak', cellPadding: { top: 3, bottom: 3, left: 3, right: 3 }, minCellWidth: 8 },
      ...options
    });

    this.currentY = (this.doc as any).lastAutoTable.finalY + 10;
  }

  addTotals(items: { label: string; value: string; bold?: boolean }[]) {
    const startX = 125;
    // Estimate total height needed: ~6px per regular item, ~13px per bold item
    const estimatedHeight = items.reduce((h, i) => h + (i.bold ? 13 : 6), 10);
    if (this.currentY + estimatedHeight > 278) { this.doc.addPage(); this.currentY = 20; }
    this.currentY += 5;

    items.forEach((item) => {
      if (this.currentY > 275) { this.doc.addPage(); this.currentY = 20; }

      if (item.bold) {
        this.doc.setDrawColor(...BRAND_TEAL);
        this.doc.setLineWidth(0.3);
        this.doc.line(startX, this.currentY - 2, 195, this.currentY - 2);
        this.currentY += 3;

        this.doc.setFillColor(...BRAND_TEAL);
        this.doc.roundedRect(startX, this.currentY - 6, 70, 10, 1, 1, 'F');

        this.doc.setFontSize(11);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(...WHITE);
        this.doc.text(item.label, startX + 3, this.currentY);
        this.doc.text(item.value, 192, this.currentY, { align: 'right' });
        this.currentY += 8;
      } else {
        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(...NEUTRAL_TEXT_MUTED);
        this.doc.text(item.label, startX, this.currentY);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(...NEUTRAL_TEXT);
        this.doc.text(item.value, 195, this.currentY, { align: 'right' });
        this.currentY += 5.5;
      }
    });
  }

  addThankYouNote() {
    this.addNotes('Thank you', this.companySettings.pdf_footer_message || 'Thank you for your business!');
  }

  addNotes(title: string, content: string) {
    if (!content) return;

    this.currentY += 8;
    if (this.currentY > 265) { this.doc.addPage(); this.currentY = 20; }

    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...NEUTRAL_TEXT);
    this.doc.text(title, 15, this.currentY);
    this.currentY += 5;

    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...NEUTRAL_TEXT_MUTED);
    const lines = this.doc.splitTextToSize(content, 175);

    this.doc.setFillColor(...NEUTRAL_BG);
    this.doc.setDrawColor(...NEUTRAL_BORDER);
    this.doc.setLineWidth(0.1);
    this.doc.roundedRect(15, this.currentY - 3, 180, lines.length * 4 + 4, 1, 1, 'FD');
    this.currentY += 1;

    lines.forEach((line: string) => {
      if (this.currentY > 270) { this.doc.addPage(); this.currentY = 20; }
      this.doc.text(line, 20, this.currentY);
      this.currentY += 4;
    });

    this.currentY += 3;
  }

  // A prominent "how much do I owe" box, meant to sit right after Report
  // Details on page 1 - the full totals block at the end of the report
  // answers the same question but is easy to miss on a multi-page PDF.
  addSummaryBox(hours: number, servicesTotal: number, suppliesTotal: number) {
    const total = servicesTotal + suppliesTotal;
    const boxHeight = 30;

    if (this.currentY + boxHeight > 272) { this.doc.addPage(); this.currentY = 20; }

    const startY = this.currentY;
    this.doc.setFillColor(...TEAL_WASH);
    this.doc.setDrawColor(...BRAND_TEAL);
    this.doc.setLineWidth(0.4);
    this.doc.roundedRect(15, startY, 180, boxHeight, 2, 2, 'FD');

    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...TEAL_INK);
    this.doc.text('TOTAL AMOUNT DUE', 22, startY + 9);

    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...TEAL_DEEP);
    this.doc.text(`$${total.toFixed(2)}`, 22, startY + 22);

    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...NEUTRAL_TEXT_MUTED);
    let breakdownY = startY + 9;
    this.doc.text(`Hours: ${hours.toFixed(1)}h`, 193, breakdownY, { align: 'right' });
    breakdownY += 6;
    this.doc.text(`Services: $${servicesTotal.toFixed(2)}`, 193, breakdownY, { align: 'right' });
    if (suppliesTotal > 0) {
      breakdownY += 6;
      this.doc.text(`Supplies: $${suppliesTotal.toFixed(2)}`, 193, breakdownY, { align: 'right' });
    }

    this.currentY = startY + boxHeight + 8;
  }

  /**
   * Renders the standard service + supplies tables, breakdown, and totals block.
   * Used by monthly, project, and public reports so all PDFs are consistent.
   */
  addClientReportSections(
    tasks: ReportTask[],
    getProject: (id: string) => ReportProject | undefined,
    hourlyRate: number | ((task: ReportTask) => number)
  ) {
    // Rate can vary by year (client.yearlyRates), so callers whose tasks span
    // more than one year pass a resolver instead of a flat number.
    const getRate = typeof hourlyRate === 'function' ? hourlyRate : () => hourlyRate;

    // Newest first, regardless of what order the caller passed them in
    const sortedTasks = [...tasks].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    const servicesTasks = sortedTasks.filter(t => t.type !== 'insumos');
    const suppliesTasks = sortedTasks.filter(t => t.type === 'insumos');

    // ── At-a-glance summary, up front ───────────────────────────────────
    // The full totals block at the end of the report answers "how much do
    // I owe" too, but on a multi-page report that's buried on the last
    // page. Clients want that number without hunting for it.
    const upfrontHours    = servicesTasks.reduce((s, t) => s + (t.hours || 0), 0);
    const upfrontServices = servicesTasks.reduce((s, t) => s + (t.hours || 0) * getRate(t), 0);
    const upfrontSupplies = suppliesTasks.reduce((s, t) => s + (t.cost || 0), 0);
    this.addSummaryBox(upfrontHours, upfrontServices, upfrontSupplies);

    // ── Services table ────────────────────────────────────────────────
    if (servicesTasks.length > 0) {
      this.addSectionTitle('Services', 30);

      const servicesRows = servicesTasks.map(task => [
        format(new Date(task.date), 'MMM d, yyyy'),
        getProject(task.projectId)?.name || '—',
        task.type === 'incident' ? 'Incident' :
        task.type === 'problem' ? 'Problem' :
        task.type === 'change' ? 'Change' : 'Request',
        task.description,
        `${(task.hours || 0).toFixed(1)}h`,
        `$${((task.hours || 0) * getRate(task)).toFixed(2)}`
      ]);

      const servicesTotal = servicesTasks.reduce((s, t) => s + (t.hours || 0) * getRate(t), 0);
      const totalHoursStr = `${servicesTasks.reduce((s, t) => s + (t.hours || 0), 0).toFixed(1)}h`;

      // Total row appended as a styled body row (more reliable than foot across jspdf-autotable versions)
      const servicesTotalRow = [
        { content: 'Total', colSpan: 4, styles: { fontStyle: 'bold', halign: 'right' as const, fillColor: NEUTRAL_ROW, textColor: NEUTRAL_TEXT } },
        { content: totalHoursStr, styles: { fontStyle: 'bold', halign: 'center' as const, fillColor: NEUTRAL_ROW, textColor: NEUTRAL_TEXT } },
        { content: `$${servicesTotal.toFixed(2)}`, styles: { fontStyle: 'bold', halign: 'right' as const, fillColor: NEUTRAL_ROW, textColor: NEUTRAL_TEXT } }
      ];

      this.addTable(
        ['Date', 'Project', 'Type', 'Description', 'Hours', 'Amount'],
        [...servicesRows, servicesTotalRow],
        {
          columnStyles: {
            0: { cellWidth: 24 },
            1: { cellWidth: 28 },
            2: { cellWidth: 20 },
            3: { cellWidth: 'auto' },
            4: { cellWidth: 18, halign: 'center' },
            5: { cellWidth: 26, halign: 'right' }
          },
          // Color the Type column by task type - same accents as the client portal
          didParseCell: (data: any) => {
            if (data.section === 'body' && data.column.index === 2) {
              const color = TASK_TYPE_COLORS[data.cell.raw as string];
              if (color) {
                data.cell.styles.textColor = color;
                data.cell.styles.fontStyle = 'bold';
              }
            }
          }
        }
      );
    }

    // ── Supplies table ────────────────────────────────────────────────
    if (suppliesTasks.length > 0) {
      this.addSectionTitle('Supplies', 30);

      const suppliesRows = suppliesTasks.map(task => [
        format(new Date(task.date), 'MMM d, yyyy'),
        getProject(task.projectId)?.name || '—',
        task.description,
        `$${(task.cost || 0).toFixed(2)}`
      ]);

      const suppliesTotal = suppliesTasks.reduce((s, t) => s + (t.cost || 0), 0);

      const suppliesTotalRow = [
        { content: 'Supplies Total', colSpan: 3, styles: { fontStyle: 'bold', halign: 'right' as const, fillColor: TEAL_WASH, textColor: TEAL_INK } },
        { content: `$${suppliesTotal.toFixed(2)}`, styles: { fontStyle: 'bold', halign: 'right' as const, fillColor: TEAL_WASH, textColor: TEAL_INK } }
      ];

      this.addTable(
        ['Date', 'Project', 'Description', 'Cost'],
        [...suppliesRows, suppliesTotalRow],
        {
          headStyles: { fillColor: BRAND_TEAL },
          columnStyles: {
            0: { cellWidth: 24 },
            1: { cellWidth: 32 },
            2: { cellWidth: 'auto' },
            3: { cellWidth: 26, halign: 'right' }
          }
        }
      );
    }

    // ── Service type breakdown ────────────────────────────────────────
    // Every non-supply type gets its own row here - this used to only
    // track incidents/requests, which silently dropped Problem/Change
    // tasks from the summary (and skewed the "% of Services" column,
    // since their hours still counted toward the total).
    const breakdownTypes: { type: string; label: string }[] = [
      { type: 'incident', label: 'Incidents' },
      { type: 'request', label: 'Requests' },
      { type: 'problem', label: 'Problems' },
      { type: 'change', label: 'Changes' }
    ];
    const breakdownGroups = breakdownTypes
      .map(({ type, label }) => ({ label, tasks: servicesTasks.filter(t => t.type === type) }))
      .filter(g => g.tasks.length > 0);

    if (breakdownGroups.length > 0) {
      this.addSectionTitle('Service Breakdown', 35);

      const servicesTotal = servicesTasks.reduce((s, t) => s + (t.hours || 0) * getRate(t), 0);
      const breakdownRows: any[][] = breakdownGroups.map(({ label, tasks }) => {
        const h = tasks.reduce((s, t) => s + (t.hours || 0), 0);
        const amt = tasks.reduce((s, t) => s + (t.hours || 0) * getRate(t), 0);
        return [
          label,
          tasks.length.toString(),
          `${h.toFixed(1)}h`,
          `$${amt.toFixed(2)}`,
          servicesTotal > 0 ? `${((amt / servicesTotal) * 100).toFixed(0)}%` : '0%'
        ];
      });

      this.addTable(
        ['Type', 'Tasks', 'Hours', 'Amount', '% of Services'],
        breakdownRows,
        {
          theme: 'grid',
          headStyles: { fillColor: BRAND_DARK },
          columnStyles: {
            0: { cellWidth: 'auto', fontStyle: 'bold' },
            1: { cellWidth: 22, halign: 'center' },
            2: { cellWidth: 25, halign: 'center' },
            3: { cellWidth: 30, halign: 'right' },
            4: { cellWidth: 30, halign: 'center' }
          },
          didParseCell: (data: any) => {
            if (data.section === 'body' && data.column.index === 0) {
              const color = TASK_TYPE_COLORS[data.cell.raw as string];
              if (color) data.cell.styles.textColor = color;
            }
          }
        }
      );
    }

    // ── Grand totals block ────────────────────────────────────────────
    const totalHours    = servicesTasks.reduce((s, t) => s + (t.hours || 0), 0);
    const servicesTotal = servicesTasks.reduce((s, t) => s + (t.hours || 0) * getRate(t), 0);
    const suppliesTotal = suppliesTasks.reduce((s, t) => s + (t.cost || 0), 0);
    const grandTotal    = servicesTotal + suppliesTotal;

    const totalsItems: { label: string; value: string; bold?: boolean }[] = [
      { label: 'Total Service Hours:', value: `${totalHours.toFixed(2)}h` },
      { label: 'Services Total:', value: `$${servicesTotal.toFixed(2)}` }
    ];
    if (suppliesTotal > 0) {
      totalsItems.push({ label: 'Supplies Total:', value: `$${suppliesTotal.toFixed(2)}` });
    }
    totalsItems.push({ label: 'Total Amount:', value: `$${grandTotal.toFixed(2)}`, bold: true });

    this.addTotals(totalsItems);

    this.addNotes(
      'Gobernanza & Operativa',
      'Las horas y tareas detalladas en este informe fueron ejecutadas bajo procedimientos de control de cambios, gestión de incidencias e integración segura (ISO/IEC 20000), garantizando la estabilidad de su entorno de producción.'
    );
  }

  addFooter() {
    const pageCount = this.doc.getNumberOfPages();
    const pageWidth = this.doc.internal.pageSize.width || this.doc.internal.pageSize.getWidth();
    const pageHeight = this.doc.internal.pageSize.height || this.doc.internal.pageSize.getHeight();
    const footerY = pageHeight - 12;

    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);

      if (this.footerContext) {
        this.doc.setFont('helvetica', 'normal');
        this.doc.setFontSize(7.5);
        this.doc.setTextColor(...NEUTRAL_TEXT_LIGHT);
        this.doc.text(this.footerContext, 14, footerY - 8);
      }

      this.doc.setDrawColor(...NEUTRAL_BORDER);
      this.doc.setLineWidth(0.5);
      this.doc.line(14, footerY - 4, pageWidth - 14, footerY - 4);

      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(8);
      this.doc.setTextColor(...NEUTRAL_TEXT_LIGHT);
      this.doc.text('Cenas IT Solutions — www.cenas.uy', 14, footerY);

      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...BRAND_DARK);
      this.doc.text('Servicios gestionados bajo estándar ISO/IEC 20000', pageWidth / 2, footerY, { align: 'center' });

      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...NEUTRAL_TEXT_LIGHT);
      this.doc.text(`Página ${i} de ${pageCount}`, pageWidth - 14, footerY, { align: 'right' });
    }
  }

  save(filename: string) {
    this.addFooter();
    this.doc.save(filename);
  }

  getDoc(): jsPDF {
    return this.doc;
  }
}
